### ISSUE TITLE
"Connecting to wallet"... GUI Linux does not start

### ISSUE THREAD

**Issue by szuwar32** [BTCgreen-Network/btcgreen-blockchain#12]
**Describe the bug**

**To Reproduce**

1.
git clone https://github.com/BTCgreen-Network/btcgreen-blockchain
cd btcgreen-blockchain
sh install.sh
. ./activate
btcgreen init
sh install-gui.sh
cd *gui
npm run electron &

2. See error:  
> btcgreen-blockchain@ electron /home/hans/btcgreen-blockchain/btcgreen-blockchain-gui
> electron .

/home/hans/btcgreen-blockchain/app.asar.unpacked/daemon
false
startUrl file:///home/hans/btcgreen-blockchain/btcgreen-blockchain-gui/build/renderer/index.html
/home/hans/btcgreen-blockchain/app.asar.unpacked/daemon
false
/home/hans/btcgreen-blockchain/app.asar.unpacked/daemon
false
Running python script
Script ../btcgreen/daemon/server.py
child process success
(node:100561) electron: The default of contextIsolation is deprecated and will be changing from false to true in a future release of Electron.  See https://github.com/electron/electron/issues/23506 for more information
No cert
Have cert
stderr: Traceback (most recent call last):
  File "../btcgreen/daemon/server.py", line 1024, in <module>
    main()
  File "../btcgreen/daemon/server.py", line 1020, in main
    return run_daemon(DEFAULT_ROOT_PATH)
  File "../btcgreen/daemon/server.py", line 1014, in run_daemon
    return asyncio.get_event_loop().run_until_complete(async_run_daemon(root_path))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "../btcgreen/daemon/server.py", line 1006, in async_run_daemon
    await ws_server.start()
  File "../btcgreen/daemon/server.py", line 143, in start
    self.websocket_server = await serve(
  File "/home/hans/btcgreen-blockchain/venv/lib/python3.8/site-packages/websockets/server.py", line 965, in __await_impl__
    server = await self._create_server()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1463, in create_server
    raise OSError(err.errno, 'error while attempting '
OSError: [Errno 98] error while attempting to bind on address ('127.0.0.1', 44276): address already in use
closing code: 1

**Expected behavior**

**Screenshots**

**Desktop**

- OS: <!-Linux Mint 20.1 Cinnamon -->
- OS Version/Flavor: 
- CPU: 

**Additional context**

**Comment by 4ntibala** [comment]
same error here  unfortunately.. Mint 20.1 Cinnamon
